// REAL PCMCI causal-discovery result — generated by scripts/build_causal_demo.py from the
// open BIDMC PPG & Respiration dataset (PhysioNet, ODC-BY). No synthetic/hand-authored data.
// Re-generate with:  conda run -n pcmci python scripts/build_causal_demo.py
import demo from './causalDemo.json';

export interface CausalNode {
  id: string;
  label: string;
  unit: string;
  autoLag: number;
}

export interface CausalLink {
  from: string;
  to: string;
  lag: number; // in samples (convert to time with meta.fs_hz)
  strength: number; // |MCI| partial correlation
  sign: 1 | -1;
  directed: boolean;
}

export interface CausalMeta {
  dataset: string;
  n_recordings: number;
  n_samples: number;
  fs_hz: number;
  method: string;
  tau_max: number;
  pc_alpha: number;
}

export const causalNodes = demo.nodes as CausalNode[];
export const causalLinks = demo.links as CausalLink[];
export const causalMeta = demo.meta as CausalMeta;

export const causalCaption =
  `Real causal discovery: ${causalMeta.method} run on ${causalMeta.n_recordings} recordings ` +
  `(${causalMeta.n_samples.toLocaleString()} samples) of the open ${causalMeta.dataset}. ` +
  `Arrows are time-lagged causal links (lag shown in ms); thickness is link strength ` +
  `(MCI partial correlation), colour is the sign. The same method runs in production on ICU ventilator time series.`;
