// REAL PCMCI causal-discovery result — generated by scripts/build_causal_demo.py from the
// open BIDMC PPG & Respiration dataset (PhysioNet, ODC-BY). No synthetic/hand-authored data.
// Re-generate with:  conda run -n pcmci python scripts/build_causal_demo.py
import demo from './causalDemo.json';

export interface CausalNode {
  id: string;
  label: string;
  unit: string;
  autoLag: number;
}

export interface CausalLink {
  from: string;
  to: string;
  lag: number; // in samples (convert to time with meta.fs_hz)
  strength: number; // |MCI| partial correlation
  sign: 1 | -1;
  directed: boolean;
}

export interface CausalMeta {
  dataset: string;
  n_recordings: number;
  n_samples: number;
  fs_hz: number;
  method: string;
  tau_max: number;
  pc_alpha: number;
}

export const causalNodes = demo.nodes as CausalNode[];
export const causalLinks = demo.links as CausalLink[];
export const causalMeta = demo.meta as CausalMeta;

export const causalCaption =
  "Causal graph discovered with PCMCI⁺ on the open BIDMC PPG/Respiration dataset. " +
  "Arrows are time-lagged causal links (lag in ms); thickness = strength, colour = sign. " +
  "Method: Runge et al., Science Advances 2019. Data: Pimentel et al., IEEE TBME 2017 (PhysioNet).";
